# -*- coding: utf-8 -*-
"""Files, exceptional handling,  logging and memory  management

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZOjWNGwRbHrH8V42eTqiJzg32IqhM6sr

1. Difference between interpreted and compiled languages

Compiled language: Code is converted into machine code before execution.
Example: C, C++

Interpreted language: Code is executed line by line by an interpreter.
Example: Python

2. What is exception handling in Python?

Exception handling is a method used to handle runtime errors so the program does not crash.

Example errors:

division by zero

file not found

invalid input

3. Purpose of the finally block

The finally block always executes, whether an exception occurs or not.

Example use:

closing files

releasing resources

4. What is logging in Python?

Logging is a process of recording events, errors, or information while a program runs.

It helps developers:

track program behavior

debug errors

5. Significance of __del__ method

__del__ is a destructor method in Python.
It is called when an object is destroyed to release resources or memory.

6. Difference between import and from ... import

import

import math
print(math.sqrt(16))

from ... import

from math import sqrt
print(sqrt(16))

Second method allows direct use of the function.

7. Handling multiple exceptions

You can use multiple except blocks.

try:
    x = int(input())
    y = 10/x
except ZeroDivisionError:
    print("Cannot divide by zero")
except ValueError:
    print("Invalid input")
8. Purpose of with statement in file handling

with automatically closes the file after use.

Example:

with open("file.txt","r") as f:
    data = f.read()
9. Difference between multithreading and multiprocessing
Multithreading	Multiprocessing
Multiple threads	Multiple processes
Shared memory	Separate memory
Faster for I/O tasks	Better for CPU tasks
10. Advantages of logging

Helps debug programs

Tracks system activity

Saves error records

Useful in large applications

11. What is memory management in Python?

Memory management means efficient allocation and release of memory during program execution.

Python manages memory automatically using garbage collection.

12. Steps in exception handling

try

except

else

finally

Example:

try:
    x = 10/2
except:
    print("Error")
else:
    print("No error")
finally:
    print("Finished")
13. Why memory management is important

Prevents memory leaks

Improves performance

Efficient resource usage

14. Role of try and except

try: code that may cause error
except: handles the error

15. Python garbage collection

Python automatically removes unused objects from memory using reference counting and garbage collector.

16. Purpose of else block

The else block runs only if no exception occurs.

17. Common logging levels

DEBUG

INFO

WARNING

ERROR

CRITICAL

18. Difference between os.fork() and multiprocessing
os.fork()	multiprocessing
Unix only	Works on all OS
Low-level	High-level
Harder to manage	Easier to use
19. Importance of closing a file

Closing a file:

saves data properly

frees memory

prevents corruption

20. Difference between read() and readline()

read() → reads entire file
readline() → reads one line at a time

21. Purpose of logging module

Python logging module is used to record program messages in log files.

22. Purpose of os module

The os module allows interaction with the operating system.

Examples:

file paths

file creation

directory operations

23. Memory management challenges

memory leaks

inefficient usage

large data processing

24. Raise exception manually
raise ValueError("Invalid value")
25. Why multithreading is important

Multithreading improves performance in tasks like:

file downloading

web requests

background processing
"""

Q1.
file = open("data.txt", "w")
file.write("Hello, this is a Python file.")
file.close()

Q2.
with open("data.txt", "r") as file:
    for line in file:
        print(line)

Q3.
try:
    file = open("data.txt", "r")
    print(file.read())
    file.close()
except FileNotFoundError:
    print("File does not exist.")

Q4.
with open("source.txt", "r") as f1:
    content = f1.read()

with open("destination.txt", "w") as f2:
    f2.write(content)

Q5.
try:
    num = 10
    result = num / 0
    print(result)
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")

Q6.
import logging

logging.basicConfig(filename="error.log", level=logging.ERROR)

try:
    num = 10 / 0
except ZeroDivisionError:
    logging.error("Division by zero error occurred")

Q7.
import logging

logging.basicConfig(level=logging.INFO)

logging.info("This is an info message")
logging.warning("This is a warning message")
logging.error("This is an error message")

Q8.
try:
    file = open("data.txt", "r")
    print(file.read())
    file.close()
except FileNotFoundError:
    print("Error: File not found.")

Q9.
lines = []

with open("data.txt", "r") as file:
    for line in file:
        lines.append(line.strip())

print(lines)

Q10.
with open("data.txt", "a") as file:
    file.write("This line is added to the file\n")

Q11.
my_dict = {"name": "Amit", "age": 25}

try:
    print(my_dict["address"])
except KeyError:
    print("Error: Key does not exist in the dictionary")

Q12.
try:
    num = int(input("Enter a number: "))
    result = 10 / num
    print(result)

except ValueError:
    print("Invalid input. Please enter a number.")

except ZeroDivisionError:
    print("Cannot divide by zero.")

"""# New section"""

Q13.
import os

if os.path.exists("data.txt"):
    file = open("data.txt", "r")
    print(file.read())
    file.close()
else:
    print("File does not exist.")

Q14.
import logging

logging.basicConfig(filename="app.log", level=logging.INFO)

logging.info("Program started")

try:
    x = 10 / 0
except ZeroDivisionError:
    logging.error("Division by zero error occurred")

Q15.
try:
    with open("data.txt", "r") as file:
        content = file.read()

        if content == "":
            print("File is empty")
        else:
            print(content)

except FileNotFoundError:
    print("File not found")

Q16.
pip install memory-profiler

from memory_profiler import profile

@profile
def memory_test():
    data = [i for i in range(100000)]
    return data

memory_test()

Q17.
numbers = [1, 2, 3, 4, 5]

with open("numbers.txt", "w") as file:
    for num in numbers:
        file.write(str(num) + "\n")

print("Numbers written to file successfully")

Q18.
import logging
from logging.handlers import RotatingFileHandler

handler = RotatingFileHandler("app.log", maxBytes=1000000, backupCount=3)

logging.basicConfig(level=logging.INFO, handlers=[handler])

logging.info("Application started")
logging.error("This is an error message")

Q19.
try:
    my_list = [1, 2, 3]
    my_dict = {"a": 10}

    print(my_list[5])      # IndexError
    print(my_dict["b"])    # KeyError

except IndexError:
    print("Index error occurred")

except KeyError:
    print("Key not found in dictionary")

Q20.
with open("data.txt", "r") as file:
    content = file.read()

print(content)